version: "3.9"

services:
  finance:
    build: ./FinanceManager
    container_name: finance_service
    ports:
      - "3001:3001"
    restart: always

  ai:
    build: ./AiManager
    container_name: ai_service
    ports:
      - "3002:3002"
    restart: always
